---
apiVersion: v1
kind: Namespace
metadata:
   name: k8s-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: k8s-application
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: test-k8s-pv-claim
      containers:
        - name: nginx
#          image: nginx:latest
          image: <image name>
          imagePullPolicy: IfNotPresent 
          volumeMounts:
            - mountPath: "/var/test"
              name: task-pv-storage 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: k8s-application
  labels:
    app: nginx-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nginx-ingress
  namespace: k8s-application
spec:
  ingressClassName: "nginx"
  tls:
   - hosts:
        - "<FQDN host name>"
  rules:
    - host: "<FQDN host name>"
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: nginx-service
               port:
                 number: 80
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-k8s-pv
  namespace: k8s-application
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/test-k8s-application"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-k8s-pv-claim
  namespace: k8s-application
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
