---
apiVersion: v1
kind: Namespace
metadata:
   name: k8s-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: k8s-application
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
#          image: nginx:latest
          image: <image name>
          imagePullPolicy: IfNotPresent 
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: k8s-application
  labels:
    app: nginx-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-nginx-ingress
  namespace: k8s-application
spec:
  ingressClassName: "nginx"
  tls:
   - hosts:
        - "<FQDN host name>"
  rules:
    - host: "<FQDN host name>"
      http:
        paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: nginx-service
               port:
                 number: 80 
